project:
  type: website
  output-dir: docs
  resources: pdfjs

website:
  title: "Shirley Toribio"
  navbar:
    right:
      - href: index.qmd
        text: About
      - text: "Data Visualizations"
        menu: 
          - data_viz.qmd
          - Netflix_Analysis.qmd
          - SQL_Proj.qmd
      - text: "Data Analysis"
        menu:
          - Pets_SriLanka.qmd
      - text: "Simulations"
        menu: 
          - Beta_Simulation.qmd
          - Bayesian_Optimization_Bernoulli.qmd
      - text: "Past Research"
        menu: 
          - SIBDS.qmd
          - tda_research.qmd
format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

