project:
  type: website
  output-dir: docs
  resources: pdfjs

website:
  title: "shirleytor.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data Visualizations"
        menu: 
          - data_viz.qmd
          - Netflix_Analysis.qmd
          - SQL_Proj.qmd
      - text: "Data Analysis"
        menu:
          - Pets_SriLanka.qmd
      - text: "Simulations"
        menu: 
          - Beta_Simulation.qmd
          - Bayesian_Optimization_Bernoulli.qmd
      - text: "Past Research"
        menu: 
          - SIBDS.qmd
      - Presentation.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

